### ISSUE TITLE
Deprecation: computed-property.override in _parser computed property

### ISSUE THREAD

**Issue by danbjork** [willviles/ember-useragent#30] opened 2019-04-02 08:12 UTC
Using Ember 3.9.0, I get this deprecation warning:

> '\'DEPRECATION: The <my-app@service:user-agent::ember220>#_parser computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.\\n

**Comment by willviles** [comment] 2019-04-02 12:58
Thanks @danbjork. I think this is caused by firing the UserAgent setter on [services/user-agent:L40](https://github.com/willviles/ember-useragent/blob/07cffe385f1bc864c8e63d14a5b511a3200aaa20/addon/services/user-agent.js#L40), which overrides the computed property on [services/user-agent:L8](https://github.com/willviles/ember-useragent/blob/07cffe385f1bc864c8e63d14a5b511a3200aaa20/addon/services/user-agent.js#L8). PRs welcome, otherwise I'll get round to looking at this soon 👍

**Comment by lpaulger** [comment] 2019-04-08 12:40
@willviles I just created a PR to address these issues. If you could review the work that would be wonderful 🙇

**Comment by buschtoens** [comment] 2019-04-08 13:13
The only reason the [`set` in L40](https://github.com/willviles/ember-useragent/blob/07cffe385f1bc864c8e63d14a5b511a3200aaa20/addon/services/user-agent.js#L40) was added is to update the CPs that depend on `_parser`. For some reason `notifyPropertyChange` did not suffice.

Maybe it's worth another try now?

**Comment by willviles** [comment] 2019-04-18 12:58
@lpaulger's fix in #31 works nicely! Released in `0.9.1`.

**Closed by willviles** 2019-04-18 12:58 UTC
Labels: bug
